### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by yuhanM01** [blueskyM01/SD_GAN_Tensorflow#2]
````ruby
I do not have the train dataset and how to get
````
@blueskyM01

**Comment by yuhanM01** [comment]
file:///home/yang/%E4%B8%8B%E8%BD%BD/timg.jpeg

**Comment by yuhanM01** [comment]
file:///home/yang/timg.jpeg

**Comment by blueskyM01** [comment]
![Fig 11](https://user-images.githubusercontent.com/33344130/55611546-6618a180-57b8-11e9-86f5-ff753cbb8a0d.png)

**Comment by blueskyM01** [comment]
https://github.com/blueskyM01/SD_GAN_Tensorflow/blob/a1e2c7acf01ce0ed5d02507674033db2e6e706ee/model.py#L34-48

**Comment by yuhanM01** [comment]
![timg](https://user-images.githubusercontent.com/49302318/55612320-89dce700-57ba-11e9-936f-50274603642b.jpeg)

**Comment by yuhanM01** [comment]
![timg](https://user-images.githubusercontent.com/49302318/55612320-89dce700-57ba-11e9-936f-50274603642b.jpeg)
@blueskyM01

**Comment by yuhanM01** [comment]
#1
